# -*- coding: utf-8 -*-
"""object_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kwcMmgVpWftNBY4mznyIRQchqQSkEtZH
"""

import numpy as np
import cv2
import torch
from google.colab.patches import cv2_imshow
from google.colab import files
print("GPU Available:", torch.cuda.is_available())
!nvidia-smi

pip install ultralytics

yolov5 = torch.hub.load('ultralytics/yolov5',
                        'yolov5s',
                        pretrained=True,
                        trust_repo=True)
print("YOLOv5 model loaded successfully.")

uploaded = files.upload()

"""## 1"""

image_path = list(uploaded.keys())[0]
print("Uploaded image:", image_path)

image = cv2.imread(image_path)
cv2_imshow(image)

results = yolov5(image)
objects = results.xyxyn[0].detach().cpu().numpy()
results.print()
results.show()

output_image = image.copy()
h, w, _ = output_image.shape
objects[:, 0:4] = objects[:, 0:4] * [w, h, w, h]

classes = yolov5.names

for obj in objects:
  if obj[-2] > 0.5:
    tl, br = obj[0:2].astype('int'), obj[2:4].astype('int')
    cv2.rectangle(output_image, tuple(tl), tuple(br), (0, 255, 0), 2)

output_filename = "output_result1.png"
cv2.imwrite(output_filename, output_image)
print(f"\nOutput image saved as {output_filename}")

"""## 2"""

yolov5 = torch.hub.load('ultralytics/yolov5', 'yolov5x')

image_path = list(uploaded.keys())[0]
print("Uploaded image:", image_path)

image = cv2.imread(image_path)
cv2_imshow(image)
results = yolov5(image)

results.print()
objects = results.xyxyn[0].detach().cpu().numpy()
output_image = image.copy()
h, w, _ = output_image.shape
objects[:, 0:4] = objects[:, 0:4] * [w, h, w, h]
classes = yolov5.names
confidence_threshold = 0.50

print("\nDetected objects:")

for obj in objects:
    confidence = obj[4]
    class_id = int(obj[5])
    if confidence >= confidence_threshold:
        class_name = classes[class_id]
        print(f"{class_name}: {confidence:.2f}")

        x1, y1, x2, y2 = obj[0:4].astype(int)
        cv2.rectangle(output_image,
                      (x1, y1),
                      (x2, y2),
                      (0, 255, 0),
                      2)
        label = f"{class_name}: {confidence:.2f}"

        text_y = y1 - 10 if y1 - 10 > 10 else y1 + 20
        cv2.putText(output_image,
                    label,
                    (x1, text_y),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.5,
                    (0, 255, 0),
                    2)

output_filename = "output_result2.png"
cv2.imwrite(output_filename, output_image)
print(f"\nOutput image saved as {output_filename}")

cv2_imshow(output_image)